wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1678807293.358196
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.9.16
      5: 0.13.11
      8:
      - 1
      - 5
